/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ProductoIndexRouteImport } from './routes/producto.index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as ProductoLoginRouteImport } from './routes/producto.login'
import { Route as VerificarIndexRouteImport } from './routes/verificar.index'
import { Route as VerificarCodigoRouteImport } from './routes/verificar.$codigo'
import { Route as AdminCertificadosIndexRouteImport } from './routes/admin.certificados.index'
import { Route as AdminCertificadosCodigoRouteImport } from './routes/admin.certificados.$codigo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ProductoIndexRoute = ProductoIndexRouteImport.update({
  id: '/producto/',
  path: '/producto/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoLoginRoute = ProductoLoginRouteImport.update({
  id: '/producto/login',
  path: '/producto/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarIndexRoute = VerificarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerificarRoute,
} as any)
const VerificarCodigoRoute = VerificarCodigoRouteImport.update({
  id: '/$codigo',
  path: '/$codigo',
  getParentRoute: () => VerificarRoute,
} as any)
const AdminCertificadosIndexRoute = AdminCertificadosIndexRouteImport.update({
  id: '/certificados/',
  path: '/certificados/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificadosCodigoRoute = AdminCertificadosCodigoRouteImport.update({
  id: '/certificados/$codigo',
  path: '/certificados/$codigo',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/verificar': typeof VerificarRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/producto/login': typeof ProductoLoginRoute
  '/verificar/$codigo': typeof VerificarCodigoRoute
  '/admin/': typeof AdminIndexRoute
  '/producto/': typeof ProductoIndexRoute
  '/verificar/': typeof VerificarIndexRoute
  '/admin/certificados/$codigo': typeof AdminCertificadosCodigoRoute
  '/admin/certificados/': typeof AdminCertificadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/producto/login': typeof ProductoLoginRoute
  '/verificar/$codigo': typeof VerificarCodigoRoute
  '/admin': typeof AdminIndexRoute
  '/producto': typeof ProductoIndexRoute
  '/verificar': typeof VerificarIndexRoute
  '/admin/certificados/$codigo': typeof AdminCertificadosCodigoRoute
  '/admin/certificados': typeof AdminCertificadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/verificar': typeof VerificarRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/producto/login': typeof ProductoLoginRoute
  '/verificar/$codigo': typeof VerificarCodigoRoute
  '/admin/': typeof AdminIndexRoute
  '/producto/': typeof ProductoIndexRoute
  '/verificar/': typeof VerificarIndexRoute
  '/admin/certificados/$codigo': typeof AdminCertificadosCodigoRoute
  '/admin/certificados/': typeof AdminCertificadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/verificar'
    | '/admin/login'
    | '/producto/$slug'
    | '/producto/login'
    | '/verificar/$codigo'
    | '/admin/'
    | '/producto/'
    | '/verificar/'
    | '/admin/certificados/$codigo'
    | '/admin/certificados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/producto/$slug'
    | '/producto/login'
    | '/verificar/$codigo'
    | '/admin'
    | '/producto'
    | '/verificar'
    | '/admin/certificados/$codigo'
    | '/admin/certificados'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/verificar'
    | '/admin/login'
    | '/producto/$slug'
    | '/producto/login'
    | '/verificar/$codigo'
    | '/admin/'
    | '/producto/'
    | '/verificar/'
    | '/admin/certificados/$codigo'
    | '/admin/certificados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  VerificarRoute: typeof VerificarRouteWithChildren
  ProductoSlugRoute: typeof ProductoSlugRoute
  ProductoLoginRoute: typeof ProductoLoginRoute
  ProductoIndexRoute: typeof ProductoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/producto/': {
      id: '/producto/'
      path: '/producto'
      fullPath: '/producto/'
      preLoaderRoute: typeof ProductoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/login': {
      id: '/producto/login'
      path: '/producto/login'
      fullPath: '/producto/login'
      preLoaderRoute: typeof ProductoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar/': {
      id: '/verificar/'
      path: '/'
      fullPath: '/verificar/'
      preLoaderRoute: typeof VerificarIndexRouteImport
      parentRoute: typeof VerificarRoute
    }
    '/verificar/$codigo': {
      id: '/verificar/$codigo'
      path: '/$codigo'
      fullPath: '/verificar/$codigo'
      preLoaderRoute: typeof VerificarCodigoRouteImport
      parentRoute: typeof VerificarRoute
    }
    '/admin/certificados/': {
      id: '/admin/certificados/'
      path: '/certificados'
      fullPath: '/admin/certificados/'
      preLoaderRoute: typeof AdminCertificadosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificados/$codigo': {
      id: '/admin/certificados/$codigo'
      path: '/certificados/$codigo'
      fullPath: '/admin/certificados/$codigo'
      preLoaderRoute: typeof AdminCertificadosCodigoRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCertificadosCodigoRoute: typeof AdminCertificadosCodigoRoute
  AdminCertificadosIndexRoute: typeof AdminCertificadosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCertificadosCodigoRoute: AdminCertificadosCodigoRoute,
  AdminCertificadosIndexRoute: AdminCertificadosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VerificarRouteChildren {
  VerificarCodigoRoute: typeof VerificarCodigoRoute
  VerificarIndexRoute: typeof VerificarIndexRoute
}

const VerificarRouteChildren: VerificarRouteChildren = {
  VerificarCodigoRoute: VerificarCodigoRoute,
  VerificarIndexRoute: VerificarIndexRoute,
}

const VerificarRouteWithChildren = VerificarRoute._addFileChildren(
  VerificarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  VerificarRoute: VerificarRouteWithChildren,
  ProductoSlugRoute: ProductoSlugRoute,
  ProductoLoginRoute: ProductoLoginRoute,
  ProductoIndexRoute: ProductoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
